version: '3'
services:

  # Lock dependencies
  lock:
    entrypoint: pipenv lock
    env_file: .env
    environment:
      WORKON_HOME: /var/lock
    image: lambci/lambda:build-python3.7
    volumes:
      - lock:/var/lock
      - ./:/tmp/task

  # Build lambda/layer
  build:
    entrypoint: pip install
    env_file: .env
    image: lambci/lambda:build-python3.7
    volumes:
      - lambda:/var/task
      - layer:/opt/python
      - ./:/tmp/build
    working_dir: /tmp/build

  # Package lambda/layer
  package:
    entrypoint: zip -r - .
    env_file: .env
    image: lambci/lambda:build-python3.7
    volumes:
      - lambda:/var/task
      - layer:/opt/python

  # Deploy lambda/layer to S3
  deploy:
    entrypoint: aws s3
    env_file: .env
    image: lambci/lambda:build-python3.7
    volumes:
      - ./dist:/var/task

  # Test function
  test:
    env_file: .env
    image: lambci/lambda:python3.7
    volumes:
      - lambda:/var/task
      - layer:/opt/python

volumes:
  layer:
  lambda:
  lock:
