version: '3'
services:

  # Build lambda/layer
  build:
    entrypoint: pip install
    image: lambci/lambda:build-python3.7
    volumes:
      - lambda:/var/task
      - layer:/opt/python
      - ./:/tmp
    working_dir: /tmp

  # Package lambda/layer
  dist:
    entrypoint: zip -r - .
    image: lambci/lambda:build-python3.7
    volumes:
      - lambda:/var/task
      - layer:/opt/python

  # Test function
  test:
    env_file: .env
    image: lambci/lambda:python3.7
    volumes:
      - lambda:/var/task
      - layer:/opt/python

  # Develop function
  dev:
    command: /bin/bash
    env_file: .env
    image: lambci/lambda:build-python3.7
    volumes:
      - layer:/opt/python
      - ./:/var/task

volumes:
  lambda:
  layer:
